<?php

namespace MarmiWildBundle\Repository;

/**
 * Rec_IngRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class Rec_IngRepository extends \Doctrine\ORM\EntityRepository
{
}
